- hosts: all
  tasks:
    #- name: install kitty terminfo
    # apt:
    #    name: kitty-terminfo
  roles:
    - role: dhcp
    - role: tftp
    - role: http
    - role: nfs
    #- role: pxelinux
    - role: ipxe
    - role: ubuntu
